name: 'airbnb'
version: '1.0.0'

# profile đã được setup trong ~/.dbt/profiles.yml đây là chọn profile sử dụng cho project này. 
profile: 'airbnb'



model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]



clean-targets: # khi chạy `dbt clean` mấy folder này sẽ bị xóa
  - "target"
  - "dbt_packages"


on-run-start:
  # - "CREATE TABLE IF NOT EXISTS {{ target.schema }}.audit_log ( model_name STRING, run_timestamp TIMESTAMP )"
  - "CREATE TABLE IF NOT EXISTS airbnb.audit_log (model_name varchar(255), run_timestamp TIMESTAMP )" 
  # sửa lại vì mình dùng postgres. 


seeds:
  # Builds seeds into '<your_schema_name>_raw'
  airbnb:
    +schema: raw_airbnb

models:
  airbnb:
    +materialized: view #  mode mặc định là view, từng model cụ thể thế nào thì override ở dưới
    src:
      +materialized: ephemeral
      # +materialized: view
    dim:
      +materialized: table
    fct:
      +materialized: table
